name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: minimal test
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-20.04','macos-latest']
        python-version: [ '3.9' ]
        include:
          - os-version: 'ubuntu-20.04'
            python-version: '3.6'
          - os-version: 'ubuntu-20.04'
            python-version: '3.7'
          - os-version: 'ubuntu-20.04'
            python-version: '3.8'           
          - os-version: 'ubuntu-20.04'
            python-version: '3.10'             
    runs-on: ${{ matrix.os-version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}   
      - name: update pip
        run: |
          python3 -m pip install --upgrade pip        
      - name: install
        run: |
          pip install .
      - name: minimal test
        run: |
          pyreversi -w 5 -b 5 -n 3 -afs           
      - name: minimal test with board
        run: |
          pyreversi -w 0 -b 0 -af 
